
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjbnompenijpbnpakpwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqYm5vbXBlbmlqcGJucGFrcHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzEwNzksImV4cCI6MjA2MDIwNzA3OX0.lZV9etn-8FhgRuxFQwGCQplw-iB4M4kvqR2m7ziUqKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
